name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code # toma lo q esta en nuestro repositorio
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # ve bn adentro en la busqueda del historial de commits
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        echo "Iniciando login"
        docker login -u $DOCKER_USER  -p $DOCKER_PASSWORD
        echo "Fin login"
    - name: Build docker image
      run: |
         docker build --tag broken1451/graphql:0.0.2 .
    - name: Push docker image
      run: |
         docker push broken1451/graphql:0.0.2

    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
